// Generated by `wit-bindgen` 0.48.1. DO NOT EDIT!
#ifndef __BINDINGS_SQLITE_CLI_UNIFIED_H
#define __BINDINGS_SQLITE_CLI_UNIFIED_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct sqlite_cli_unified_string_t {
  uint8_t*ptr;
  size_t len;
} sqlite_cli_unified_string_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} sqlite_cli_unified_list_u8_t;

// Unified SQL value representation. Used for function arguments,
// function results, parameter binding, and row data.
typedef struct sqlite_extension_types_sql_value_t {
  uint8_t tag;
  union {
    int64_t     integer;
    double     real;
    sqlite_cli_unified_string_t     text;
    sqlite_cli_unified_list_u8_t     blob;
  } val;
} sqlite_extension_types_sql_value_t;

// SQL NULL.
#define SQLITE_EXTENSION_TYPES_SQL_VALUE_NULL 0
// Signed 64-bit integer.
#define SQLITE_EXTENSION_TYPES_SQL_VALUE_INTEGER 1
// IEEE 754 double-precision floating point.
#define SQLITE_EXTENSION_TYPES_SQL_VALUE_REAL 2
// UTF-8 text.
#define SQLITE_EXTENSION_TYPES_SQL_VALUE_TEXT 3
// Binary blob.
#define SQLITE_EXTENSION_TYPES_SQL_VALUE_BLOB 4

// SQLite error carrying both primary and extended result codes.
typedef struct sqlite_extension_types_sqlite_error_t {
  int32_t   code;
  int32_t   extended_code;
  sqlite_cli_unified_string_t   message;
} sqlite_extension_types_sqlite_error_t;

// Flags describing a SQL function's properties. Mirror SQLite's
// SQLITE_DETERMINISTIC / SQLITE_DIRECTONLY / SQLITE_INNOCUOUS bits.
typedef uint8_t sqlite_extension_types_function_flags_t;

// Same inputs always produce the same output.
#define SQLITE_EXTENSION_TYPES_FUNCTION_FLAGS_DETERMINISTIC (1 << 0)
// May have side effects; cannot be used in indexes, CHECK
// constraints, generated columns, etc.
#define SQLITE_EXTENSION_TYPES_FUNCTION_FLAGS_DIRECT_ONLY (1 << 1)
// Function is provably safe to use in arbitrary trusted SQL.
#define SQLITE_EXTENSION_TYPES_FUNCTION_FLAGS_INNOCUOUS (1 << 2)

// Authorization action codes. Mirrors SQLite's SQLITE_* action
// constants passed to the authorizer callback.
typedef uint8_t sqlite_extension_types_auth_action_t;

#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_INDEX 0
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TABLE 1
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TEMP_INDEX 2
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TEMP_TABLE 3
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TEMP_TRIGGER 4
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TEMP_VIEW 5
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TRIGGER 6
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_VIEW 7
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DELETE 8
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_INDEX 9
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TABLE 10
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TEMP_INDEX 11
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TEMP_TABLE 12
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TEMP_TRIGGER 13
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TEMP_VIEW 14
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TRIGGER 15
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_VIEW 16
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_INSERT 17
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_PRAGMA 18
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_READ 19
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_SELECT 20
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_TRANSACTION 21
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_UPDATE 22
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_ATTACH 23
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DETACH 24
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_ALTER_TABLE 25
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_REINDEX 26
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_ANALYZE 27
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_VTABLE 28
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_VTABLE 29
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_FUNCTION 30
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_SAVEPOINT 31
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_RECURSIVE 32

// Result returned from an authorizer callback.
typedef uint8_t sqlite_extension_types_auth_result_t;

// Permit the action.
#define SQLITE_EXTENSION_TYPES_AUTH_RESULT_OK 0
// Deny the action with an error.
#define SQLITE_EXTENSION_TYPES_AUTH_RESULT_DENY 1
// Silently ignore the action (treat as no-op).
#define SQLITE_EXTENSION_TYPES_AUTH_RESULT_IGNORE 2

// Type of row change reported to an update hook.
typedef uint8_t sqlite_extension_types_update_operation_t;

#define SQLITE_EXTENSION_TYPES_UPDATE_OPERATION_INSERT 0
#define SQLITE_EXTENSION_TYPES_UPDATE_OPERATION_UPDATE 1
#define SQLITE_EXTENSION_TYPES_UPDATE_OPERATION_DELETE 2

// Log severity levels.
typedef uint8_t sqlite_extension_types_log_level_t;

#define SQLITE_EXTENSION_TYPES_LOG_LEVEL_ERROR 0
#define SQLITE_EXTENSION_TYPES_LOG_LEVEL_WARN 1
#define SQLITE_EXTENSION_TYPES_LOG_LEVEL_INFO 2
#define SQLITE_EXTENSION_TYPES_LOG_LEVEL_DEBUG 3
#define SQLITE_EXTENSION_TYPES_LOG_LEVEL_TRACE 4

typedef struct {
  bool is_some;
  sqlite_cli_unified_string_t val;
} sqlite_cli_unified_option_string_t;

// Per-column metadata returned by schema introspection.
typedef struct sqlite_extension_types_column_info_t {
  sqlite_cli_unified_string_t   name;
  sqlite_cli_unified_option_string_t   decl_type;
  sqlite_cli_unified_option_string_t   database;
  sqlite_cli_unified_option_string_t   table;
  sqlite_cli_unified_option_string_t   origin;
} sqlite_extension_types_column_info_t;

typedef struct {
  sqlite_extension_types_column_info_t *ptr;
  size_t len;
} sqlite_extension_types_list_column_info_t;

typedef struct {
  sqlite_cli_unified_string_t *ptr;
  size_t len;
} sqlite_cli_unified_list_string_t;

// Per-table metadata returned by schema introspection.
typedef struct sqlite_extension_types_table_info_t {
  sqlite_cli_unified_string_t   name;
  sqlite_extension_types_list_column_info_t   columns;
  sqlite_cli_unified_list_string_t   pk_columns;
} sqlite_extension_types_table_info_t;

typedef struct {
  sqlite_extension_types_sql_value_t *ptr;
  size_t len;
} sqlite_extension_types_list_sql_value_t;

typedef struct {
  sqlite_extension_types_list_sql_value_t *ptr;
  size_t len;
} sqlite_extension_types_list_list_sql_value_t;

// Result of an `execute` call: column names, row data, change counts.
typedef struct sqlite_extension_types_query_result_t {
  sqlite_cli_unified_list_string_t   columns;
  sqlite_extension_types_list_list_sql_value_t   rows;
  // Rows changed by INSERT/UPDATE/DELETE.
  int64_t   changes;
  // Last inserted rowid.
  int64_t   last_insert_rowid;
} sqlite_extension_types_query_result_t;

// HTTP method. Mirrors `wasi:http/types.method`.
typedef struct sqlite_extension_http_method_t {
  uint8_t tag;
  union {
    sqlite_cli_unified_string_t     other;
  } val;
} sqlite_extension_http_method_t;

#define SQLITE_EXTENSION_HTTP_METHOD_GET 0
#define SQLITE_EXTENSION_HTTP_METHOD_HEAD 1
#define SQLITE_EXTENSION_HTTP_METHOD_POST 2
#define SQLITE_EXTENSION_HTTP_METHOD_PUT 3
#define SQLITE_EXTENSION_HTTP_METHOD_DELETE 4
#define SQLITE_EXTENSION_HTTP_METHOD_CONNECT 5
#define SQLITE_EXTENSION_HTTP_METHOD_OPTIONS 6
#define SQLITE_EXTENSION_HTTP_METHOD_TRACE 7
#define SQLITE_EXTENSION_HTTP_METHOD_PATCH 8
// Non-standard / extension method.
#define SQLITE_EXTENSION_HTTP_METHOD_OTHER 9

// URL scheme. Mirrors `wasi:http/types.scheme`.
typedef struct sqlite_extension_http_scheme_t {
  uint8_t tag;
  union {
    sqlite_cli_unified_string_t     other;
  } val;
} sqlite_extension_http_scheme_t;

#define SQLITE_EXTENSION_HTTP_SCHEME_HTTP 0
#define SQLITE_EXTENSION_HTTP_SCHEME_HTTPS 1
// Non-standard scheme.
#define SQLITE_EXTENSION_HTTP_SCHEME_OTHER 2

// Header field — name + raw bytes value (per wasi-http).
typedef struct sqlite_extension_http_field_t {
  sqlite_cli_unified_string_t   f0;
  sqlite_cli_unified_list_u8_t   f1;
} sqlite_extension_http_field_t;

typedef struct {
  bool is_some;
  sqlite_extension_http_scheme_t val;
} sqlite_extension_http_option_scheme_t;

typedef struct {
  sqlite_extension_http_field_t *ptr;
  size_t len;
} sqlite_cli_unified_list_field_t;

typedef struct {
  bool is_some;
  sqlite_cli_unified_list_u8_t val;
} sqlite_cli_unified_option_list_u8_t;

typedef struct {
  bool is_some;
  uint32_t val;
} sqlite_cli_unified_option_u32_t;

// Outgoing request. Mirrors `wasi:http/types.outgoing-request`
// but flattened from the resource-based wasi-http form into a
// single value-typed record.
typedef struct sqlite_extension_http_request_t {
  sqlite_extension_http_method_t   method;
  sqlite_extension_http_option_scheme_t   scheme;
  // Host (with optional port), e.g. "example.com:8443".
  sqlite_cli_unified_option_string_t   authority;
  // Path + query, e.g. "/api/v1/things?id=42".
  sqlite_cli_unified_option_string_t   path_with_query;
  sqlite_cli_unified_list_field_t   headers;
  sqlite_cli_unified_option_list_u8_t   body;
  sqlite_cli_unified_option_u32_t   timeout_ms;
} sqlite_extension_http_request_t;

// Incoming response. Mirrors `wasi:http/types.incoming-response`
// in flattened form.
typedef struct sqlite_extension_http_response_t {
  uint16_t   status;
  sqlite_cli_unified_list_field_t   headers;
  sqlite_cli_unified_list_u8_t   body;
} sqlite_extension_http_response_t;

// HTTP error variants. Mirrors the shape of
// `wasi:http/types.error-code` at a higher level.
typedef struct sqlite_extension_http_http_error_t {
  uint8_t tag;
  union {
    sqlite_cli_unified_string_t     invalid_url;
    sqlite_cli_unified_string_t     connection_error;
    sqlite_cli_unified_string_t     protocol_error;
    sqlite_cli_unified_string_t     other;
  } val;
} sqlite_extension_http_http_error_t;

#define SQLITE_EXTENSION_HTTP_HTTP_ERROR_INVALID_URL 0
#define SQLITE_EXTENSION_HTTP_HTTP_ERROR_TIMED_OUT 1
#define SQLITE_EXTENSION_HTTP_HTTP_ERROR_CONNECTION_ERROR 2
#define SQLITE_EXTENSION_HTTP_HTTP_ERROR_PROTOCOL_ERROR 3
#define SQLITE_EXTENSION_HTTP_HTTP_ERROR_OTHER 4

typedef struct {
  bool is_err;
  union {
    sqlite_extension_http_response_t ok;
    sqlite_extension_http_http_error_t err;
  } val;
} sqlite_extension_http_result_response_http_error_t;

typedef sqlite_extension_http_method_t sqlite_extension_policy_method_t;

// One capability per host-imported interface.
typedef struct sqlite_extension_policy_capability_t {
  uint8_t tag;
} sqlite_extension_policy_capability_t;

// Basic SQL execution (sqlite:extension/spi).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_SPI 0
// Prepared statement handles (sqlite:extension/prepared).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_PREPARED 1
// Transaction control (sqlite:extension/transaction). Mutating.
#define SQLITE_EXTENSION_POLICY_CAPABILITY_TRANSACTION 2
// Schema introspection (sqlite:extension/schema).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_SCHEMA 3
// Persistent per-extension state (sqlite:extension/state).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_STATE 4
// Bounded in-memory cache (sqlite:extension/cache).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_CACHE 5
// Random number generation (sqlite:extension/random).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_RANDOM 6
// Unicode text utilities (sqlite:extension/text).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_TEXT 7
// Cryptographic hashing (sqlite:extension/hashing).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_HASHING 8
// Encoding helpers (sqlite:extension/encoding).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_ENCODING 9
// Outbound HTTP (sqlite:extension/http).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_HTTP 10

typedef struct {
  sqlite_extension_policy_method_t *ptr;
  size_t len;
} sqlite_extension_policy_list_method_t;

typedef struct {
  bool is_some;
  sqlite_extension_policy_list_method_t val;
} sqlite_extension_policy_option_list_method_t;

typedef struct {
  bool is_some;
  uint64_t val;
} sqlite_cli_unified_option_u64_t;

// Outbound HTTP policy. Applied by the host's `http::handle`
// implementation to every request the extension makes.
typedef struct sqlite_extension_policy_http_policy_t {
  // Allowlist of hostnames the extension may connect to. Entries
  // may use a leading `*.` for a wildcard suffix. Empty list
  // means no hosts permitted.
  sqlite_cli_unified_list_string_t   allowed_hosts;
  // Optional method restriction. None = any method allowed.
  sqlite_extension_policy_option_list_method_t   allowed_methods;
  // Maximum response body bytes the host will return to the
  // extension. Larger responses are truncated or errored.
  sqlite_cli_unified_option_u64_t   max_body_bytes;
  // Per-request wall-clock timeout. Overrides any timeout the
  // extension passes in the request.
  sqlite_cli_unified_option_u32_t   timeout_ms;
} sqlite_extension_policy_http_policy_t;

// Filesystem policy. Reserved for future use; no host interfaces
// currently grant fs access. The shape is sketched so consumers
// can prepare for it.
typedef struct sqlite_extension_policy_fs_policy_t {
  // Allowlist of host-path prefixes the extension may read from.
  sqlite_cli_unified_list_string_t   readable_prefixes;
  // Allowlist of host-path prefixes the extension may write to.
  sqlite_cli_unified_list_string_t   writable_prefixes;
  // Cap on cumulative bytes the extension may write per call.
  sqlite_cli_unified_option_u64_t   max_write_bytes_per_call;
} sqlite_extension_policy_fs_policy_t;

typedef struct {
  bool is_some;
  sqlite_extension_policy_http_policy_t val;
} sqlite_extension_policy_option_http_policy_t;

typedef struct {
  bool is_some;
  sqlite_extension_policy_fs_policy_t val;
} sqlite_extension_policy_option_fs_policy_t;

typedef struct {
  sqlite_extension_policy_capability_t *ptr;
  size_t len;
} sqlite_extension_policy_list_capability_t;

// Options the host passes at load time.
typedef struct sqlite_extension_policy_load_options_t {
  // wasmtime fuel budget. Reset before each guest invocation
  // (per-call semantics). None = unlimited.
  sqlite_cli_unified_option_u64_t   fuel_per_call;
  // Hard cap on the extension's linear memory in bytes.
  sqlite_cli_unified_option_u64_t   memory_limit_bytes;
  // Wall-clock deadline per guest invocation. Enforced via
  // epoch interruption on runtimes that support it; advisory
  // only on those that don't.
  sqlite_cli_unified_option_u64_t   epoch_deadline_ms;
  // HTTP policy. Required if `grant` contains `capability::http`.
  sqlite_extension_policy_option_http_policy_t   http_policy;
  // Filesystem policy. Reserved.
  sqlite_extension_policy_option_fs_policy_t   fs_policy;
  // Allow-list of capabilities granted to this extension.
  // Anything not in this list is denied. Fail-closed.
  sqlite_extension_policy_list_capability_t   grant;
} sqlite_extension_policy_load_options_t;

// Errors a loader may raise when policy refuses a load or call.
typedef struct sqlite_extension_policy_policy_error_t {
  uint8_t tag;
  union {
    sqlite_extension_policy_capability_t     capability_not_granted;
    sqlite_extension_policy_capability_t     capability_not_declared;
    sqlite_cli_unified_string_t     host_not_allowed;
    sqlite_extension_policy_method_t     method_not_allowed;
  } val;
} sqlite_extension_policy_policy_error_t;

// Extension declared a capability the host did not grant.
// The variant payload is the missing capability.
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_CAPABILITY_NOT_GRANTED 0
// Extension tried to use a capability it never declared.
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_CAPABILITY_NOT_DECLARED 1
// An HTTP request was refused by `http-policy.allowed-hosts`.
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_HOST_NOT_ALLOWED 2
// An HTTP request used a method outside `allowed-methods`.
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_METHOD_NOT_ALLOWED 3
// `grant` includes `http` but `http-policy` was None.
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_MISSING_HTTP_POLICY 4
// Resource limit reached.
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_FUEL_EXHAUSTED 5
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_MEMORY_LIMIT_EXCEEDED 6
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_EPOCH_DEADLINE_EXCEEDED 7

typedef sqlite_extension_types_function_flags_t sqlite_extension_metadata_function_flags_t;

typedef sqlite_extension_policy_capability_t sqlite_extension_metadata_capability_t;

// One scalar SQL function declared by the extension.
typedef struct sqlite_extension_metadata_scalar_function_spec_t {
  // Guest-assigned function ID. Echoed back in scalar-function.call.
  uint64_t   id;
  // SQL name visible inside the database.
  sqlite_cli_unified_string_t   name;
  // Number of arguments; -1 means variadic.
  int32_t   num_args;
  sqlite_extension_metadata_function_flags_t   func_flags;
} sqlite_extension_metadata_scalar_function_spec_t;

// One aggregate (or window) SQL function declared by the extension.
typedef struct sqlite_extension_metadata_aggregate_function_spec_t {
  uint64_t   id;
  sqlite_cli_unified_string_t   name;
  int32_t   num_args;
  sqlite_extension_metadata_function_flags_t   func_flags;
  // True if this aggregate also implements window-function ops
  // (value() + inverse()).
  bool   is_window;
} sqlite_extension_metadata_aggregate_function_spec_t;

// One custom collation declared by the extension.
typedef struct sqlite_extension_metadata_collation_spec_t {
  uint64_t   id;
  sqlite_cli_unified_string_t   name;
} sqlite_extension_metadata_collation_spec_t;

typedef struct {
  sqlite_extension_metadata_scalar_function_spec_t *ptr;
  size_t len;
} sqlite_extension_metadata_list_scalar_function_spec_t;

typedef struct {
  sqlite_extension_metadata_aggregate_function_spec_t *ptr;
  size_t len;
} sqlite_extension_metadata_list_aggregate_function_spec_t;

typedef struct {
  sqlite_extension_metadata_collation_spec_t *ptr;
  size_t len;
} sqlite_extension_metadata_list_collation_spec_t;

typedef struct {
  sqlite_extension_metadata_capability_t *ptr;
  size_t len;
} sqlite_extension_metadata_list_capability_t;

// Full extension manifest, returned from `describe()`.
typedef struct sqlite_extension_metadata_manifest_t {
  sqlite_cli_unified_string_t   name;
  sqlite_cli_unified_string_t   version;
  sqlite_extension_metadata_list_scalar_function_spec_t   scalar_functions;
  sqlite_extension_metadata_list_aggregate_function_spec_t   aggregate_functions;
  sqlite_extension_metadata_list_collation_spec_t   collations;
  // True if the extension also exports an `authorizer` interface.
  bool   has_authorizer;
  // True if the extension also exports an `update-hook` interface.
  bool   has_update_hook;
  // True if the extension also exports a `commit-hook` interface.
  bool   has_commit_hook;
  // REQUIRED: every host capability the extension imports MUST be
  // listed here. The loader compares this against
  // `load-options.grant` and refuses to load if any item is
  // missing from the grant list. Empty list = no host
  // capabilities used (extension is pure / only uses its own
  // allocator).
  sqlite_extension_metadata_list_capability_t   declared_capabilities;
} sqlite_extension_metadata_manifest_t;

typedef sqlite_extension_types_sql_value_t sqlite_wasm_fts5_slot_sql_value_t;

typedef sqlite_extension_metadata_manifest_t sqlite_wasm_fts5_slot_manifest_t;

typedef struct {
  sqlite_wasm_fts5_slot_sql_value_t *ptr;
  size_t len;
} sqlite_wasm_fts5_slot_list_sql_value_t;

typedef struct {
  bool is_err;
  union {
    sqlite_wasm_fts5_slot_sql_value_t ok;
    sqlite_cli_unified_string_t err;
  } val;
} sqlite_wasm_fts5_slot_result_sql_value_string_t;

typedef sqlite_extension_types_sql_value_t sqlite_wasm_json1_slot_sql_value_t;

typedef sqlite_extension_metadata_manifest_t sqlite_wasm_json1_slot_manifest_t;

typedef struct {
  sqlite_wasm_json1_slot_sql_value_t *ptr;
  size_t len;
} sqlite_wasm_json1_slot_list_sql_value_t;

typedef struct {
  bool is_err;
  union {
    sqlite_wasm_json1_slot_sql_value_t ok;
    sqlite_cli_unified_string_t err;
  } val;
} sqlite_wasm_json1_slot_result_sql_value_string_t;

typedef sqlite_extension_types_sql_value_t sqlite_wasm_rtree_slot_sql_value_t;

typedef sqlite_extension_metadata_manifest_t sqlite_wasm_rtree_slot_manifest_t;

typedef struct {
  sqlite_wasm_rtree_slot_sql_value_t *ptr;
  size_t len;
} sqlite_wasm_rtree_slot_list_sql_value_t;

typedef struct {
  bool is_err;
  union {
    sqlite_wasm_rtree_slot_sql_value_t ok;
    sqlite_cli_unified_string_t err;
  } val;
} sqlite_wasm_rtree_slot_result_sql_value_string_t;

typedef sqlite_extension_types_sql_value_t sqlite_wasm_geopoly_slot_sql_value_t;

typedef sqlite_extension_metadata_manifest_t sqlite_wasm_geopoly_slot_manifest_t;

typedef struct {
  sqlite_wasm_geopoly_slot_sql_value_t *ptr;
  size_t len;
} sqlite_wasm_geopoly_slot_list_sql_value_t;

typedef struct {
  bool is_err;
  union {
    sqlite_wasm_geopoly_slot_sql_value_t ok;
    sqlite_cli_unified_string_t err;
  } val;
} sqlite_wasm_geopoly_slot_result_sql_value_string_t;

typedef sqlite_extension_types_sql_value_t sqlite_wasm_demo_slot_sql_value_t;

typedef sqlite_extension_metadata_manifest_t sqlite_wasm_demo_slot_manifest_t;

typedef struct {
  sqlite_wasm_demo_slot_sql_value_t *ptr;
  size_t len;
} sqlite_wasm_demo_slot_list_sql_value_t;

typedef struct {
  bool is_err;
  union {
    sqlite_wasm_demo_slot_sql_value_t ok;
    sqlite_cli_unified_string_t err;
  } val;
} sqlite_wasm_demo_slot_result_sql_value_string_t;

typedef sqlite_extension_metadata_manifest_t sqlite_wasm_extension_loader_manifest_t;

typedef sqlite_extension_policy_load_options_t sqlite_wasm_extension_loader_load_options_t;

// Errors the loader may raise (file not found, instantiate
// failure, policy refusal, ...).
typedef struct sqlite_wasm_extension_loader_loader_error_t {
  int32_t   code;
  sqlite_cli_unified_string_t   message;
} sqlite_wasm_extension_loader_loader_error_t;

typedef struct {
  bool is_err;
  union {
    sqlite_wasm_extension_loader_manifest_t ok;
    sqlite_wasm_extension_loader_loader_error_t err;
  } val;
} sqlite_wasm_extension_loader_result_manifest_loader_error_t;

typedef struct {
  bool is_err;
  union {
    sqlite_wasm_extension_loader_loader_error_t err;
  } val;
} sqlite_wasm_extension_loader_result_void_loader_error_t;

typedef struct {
  sqlite_wasm_extension_loader_manifest_t *ptr;
  size_t len;
} sqlite_wasm_extension_loader_list_manifest_t;

// Archive information
typedef struct sqlite_wasm_zip_operations_archive_info_t {
  sqlite_cli_unified_string_t   name;
  sqlite_cli_unified_string_t   version;
  sqlite_cli_unified_list_string_t   supported_methods;
} sqlite_wasm_zip_operations_archive_info_t;

// Error codes
typedef uint8_t sqlite_wasm_zip_operations_error_code_t;

#define SQLITE_WASM_ZIP_OPERATIONS_ERROR_CODE_IO_ERROR 0
#define SQLITE_WASM_ZIP_OPERATIONS_ERROR_CODE_INVALID_ARCHIVE 1
#define SQLITE_WASM_ZIP_OPERATIONS_ERROR_CODE_NOT_FOUND 2
#define SQLITE_WASM_ZIP_OPERATIONS_ERROR_CODE_PERMISSION_DENIED 3

typedef struct {
  bool is_err;
  union {
    sqlite_wasm_zip_operations_error_code_t err;
  } val;
} sqlite_wasm_zip_operations_result_void_error_code_t;

typedef struct {
  bool is_err;
  union {
    sqlite_cli_unified_list_string_t ok;
    sqlite_wasm_zip_operations_error_code_t err;
  } val;
} sqlite_wasm_zip_operations_result_list_string_error_code_t;

// Opaque handles represented as u64
typedef uint64_t exports_sqlite_wasm_low_level_db_handle_t;

typedef uint64_t exports_sqlite_wasm_low_level_stmt_handle_t;

// SQLite result codes
typedef uint8_t exports_sqlite_wasm_low_level_result_code_t;

#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_OK 0
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_ERROR 1
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_INTERNAL 2
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_PERM 3
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_ABORT 4
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_BUSY 5
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_LOCKED 6
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_NOMEM 7
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_READONLY 8
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_INTERRUPT 9
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_IOERR 10
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_CORRUPT 11
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_NOTFOUND 12
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_FULL 13
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_CANTOPEN 14
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_PROTOCOL 15
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_EMPTY 16
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_SCHEMA 17
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_TOOBIG 18
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_CONSTRAINT 19
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_MISMATCH 20
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_MISUSE 21
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_NOLFS 22
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_AUTH 23
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_FORMAT 24
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_RANGE 25
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_NOTADB 26
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_NOTICE 27
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_WARNING 28
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_ROW 29
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_RESULT_CODE_DONE 30

// SQLite data types
typedef uint8_t exports_sqlite_wasm_low_level_column_type_t;

#define EXPORTS_SQLITE_WASM_LOW_LEVEL_COLUMN_TYPE_INTEGER 0
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_COLUMN_TYPE_FLOAT 1
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_COLUMN_TYPE_TEXT 2
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_COLUMN_TYPE_BLOB 3
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_COLUMN_TYPE_NULL 4

// Open flags
typedef uint8_t exports_sqlite_wasm_low_level_open_flags_t;

#define EXPORTS_SQLITE_WASM_LOW_LEVEL_OPEN_FLAGS_READONLY (1 << 0)
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_OPEN_FLAGS_READWRITE (1 << 1)
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_OPEN_FLAGS_CREATE (1 << 2)
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_OPEN_FLAGS_MEMORY (1 << 3)
#define EXPORTS_SQLITE_WASM_LOW_LEVEL_OPEN_FLAGS_URI (1 << 4)

typedef struct {
  bool is_err;
  union {
    exports_sqlite_wasm_low_level_db_handle_t ok;
    exports_sqlite_wasm_low_level_result_code_t err;
  } val;
} exports_sqlite_wasm_low_level_result_db_handle_result_code_t;

typedef struct {
  bool is_err;
  union {
    sqlite_cli_unified_string_t ok;
    exports_sqlite_wasm_low_level_result_code_t err;
  } val;
} exports_sqlite_wasm_low_level_result_string_result_code_t;

typedef struct {
  bool is_err;
  union {
    exports_sqlite_wasm_low_level_stmt_handle_t ok;
    exports_sqlite_wasm_low_level_result_code_t err;
  } val;
} exports_sqlite_wasm_low_level_result_stmt_handle_result_code_t;

// SQLite value variant
typedef struct exports_sqlite_wasm_high_level_value_t {
  uint8_t tag;
  union {
    int64_t     integer;
    double     real;
    sqlite_cli_unified_string_t     text;
    sqlite_cli_unified_list_u8_t     blob;
  } val;
} exports_sqlite_wasm_high_level_value_t;

#define EXPORTS_SQLITE_WASM_HIGH_LEVEL_VALUE_NULL 0
#define EXPORTS_SQLITE_WASM_HIGH_LEVEL_VALUE_INTEGER 1
#define EXPORTS_SQLITE_WASM_HIGH_LEVEL_VALUE_REAL 2
#define EXPORTS_SQLITE_WASM_HIGH_LEVEL_VALUE_TEXT 3
#define EXPORTS_SQLITE_WASM_HIGH_LEVEL_VALUE_BLOB 4

// Error information
typedef struct exports_sqlite_wasm_high_level_database_error_t {
  int32_t   code;
  int32_t   extended_code;
  sqlite_cli_unified_string_t   message;
} exports_sqlite_wasm_high_level_database_error_t;

typedef struct {
  exports_sqlite_wasm_high_level_value_t *ptr;
  size_t len;
} exports_sqlite_wasm_high_level_list_value_t;

// Row data
typedef struct exports_sqlite_wasm_high_level_row_t {
  exports_sqlite_wasm_high_level_list_value_t   columns;
} exports_sqlite_wasm_high_level_row_t;

typedef struct {
  exports_sqlite_wasm_high_level_row_t *ptr;
  size_t len;
} exports_sqlite_wasm_high_level_list_row_t;

// Query results
typedef struct exports_sqlite_wasm_high_level_query_result_t {
  sqlite_cli_unified_list_string_t   column_names;
  exports_sqlite_wasm_high_level_list_row_t   rows;
} exports_sqlite_wasm_high_level_query_result_t;

// Execution result (for INSERT/UPDATE/DELETE)
typedef struct exports_sqlite_wasm_high_level_exec_result_t {
  int32_t   changes;
  int64_t   last_insert_rowid;
} exports_sqlite_wasm_high_level_exec_result_t;

// Open mode options
typedef uint8_t exports_sqlite_wasm_high_level_open_mode_t;

#define EXPORTS_SQLITE_WASM_HIGH_LEVEL_OPEN_MODE_READ_ONLY 0
#define EXPORTS_SQLITE_WASM_HIGH_LEVEL_OPEN_MODE_READ_WRITE 1
#define EXPORTS_SQLITE_WASM_HIGH_LEVEL_OPEN_MODE_READ_WRITE_CREATE 2
#define EXPORTS_SQLITE_WASM_HIGH_LEVEL_OPEN_MODE_MEMORY 3

typedef struct exports_sqlite_wasm_high_level_own_connection_t {
  int32_t __handle;
} exports_sqlite_wasm_high_level_own_connection_t;

typedef struct exports_sqlite_wasm_high_level_connection_t exports_sqlite_wasm_high_level_connection_t;

typedef exports_sqlite_wasm_high_level_connection_t* exports_sqlite_wasm_high_level_borrow_connection_t;

typedef struct exports_sqlite_wasm_high_level_own_statement_t {
  int32_t __handle;
} exports_sqlite_wasm_high_level_own_statement_t;

typedef struct exports_sqlite_wasm_high_level_statement_t exports_sqlite_wasm_high_level_statement_t;

typedef exports_sqlite_wasm_high_level_statement_t* exports_sqlite_wasm_high_level_borrow_statement_t;

typedef struct {
  bool is_err;
  union {
    exports_sqlite_wasm_high_level_exec_result_t ok;
    exports_sqlite_wasm_high_level_database_error_t err;
  } val;
} exports_sqlite_wasm_high_level_result_exec_result_database_error_t;

typedef struct {
  bool is_err;
  union {
    exports_sqlite_wasm_high_level_query_result_t ok;
    exports_sqlite_wasm_high_level_database_error_t err;
  } val;
} exports_sqlite_wasm_high_level_result_query_result_database_error_t;

typedef struct {
  bool is_err;
  union {
    exports_sqlite_wasm_high_level_own_statement_t ok;
    exports_sqlite_wasm_high_level_database_error_t err;
  } val;
} exports_sqlite_wasm_high_level_result_own_statement_database_error_t;

typedef struct {
  bool is_err;
  union {
    exports_sqlite_wasm_high_level_database_error_t err;
  } val;
} exports_sqlite_wasm_high_level_result_void_database_error_t;

typedef struct {
  bool is_some;
  exports_sqlite_wasm_high_level_database_error_t val;
} exports_sqlite_wasm_high_level_option_database_error_t;

typedef struct {
  bool is_some;
  exports_sqlite_wasm_high_level_row_t val;
} exports_sqlite_wasm_high_level_option_row_t;

typedef struct {
  bool is_err;
  union {
    exports_sqlite_wasm_high_level_option_row_t ok;
    exports_sqlite_wasm_high_level_database_error_t err;
  } val;
} exports_sqlite_wasm_high_level_result_option_row_database_error_t;

typedef struct {
  bool is_err;
  union {
    exports_sqlite_wasm_high_level_own_connection_t ok;
    exports_sqlite_wasm_high_level_database_error_t err;
  } val;
} exports_sqlite_wasm_high_level_result_own_connection_database_error_t;

// Unified SQL value representation. Used for function arguments,
// function results, parameter binding, and row data.
typedef struct exports_sqlite_extension_types_sql_value_t {
  uint8_t tag;
  union {
    int64_t     integer;
    double     real;
    sqlite_cli_unified_string_t     text;
    sqlite_cli_unified_list_u8_t     blob;
  } val;
} exports_sqlite_extension_types_sql_value_t;

// SQL NULL.
#define EXPORTS_SQLITE_EXTENSION_TYPES_SQL_VALUE_NULL 0
// Signed 64-bit integer.
#define EXPORTS_SQLITE_EXTENSION_TYPES_SQL_VALUE_INTEGER 1
// IEEE 754 double-precision floating point.
#define EXPORTS_SQLITE_EXTENSION_TYPES_SQL_VALUE_REAL 2
// UTF-8 text.
#define EXPORTS_SQLITE_EXTENSION_TYPES_SQL_VALUE_TEXT 3
// Binary blob.
#define EXPORTS_SQLITE_EXTENSION_TYPES_SQL_VALUE_BLOB 4

// SQLite error carrying both primary and extended result codes.
typedef struct exports_sqlite_extension_types_sqlite_error_t {
  int32_t   code;
  int32_t   extended_code;
  sqlite_cli_unified_string_t   message;
} exports_sqlite_extension_types_sqlite_error_t;

// Flags describing a SQL function's properties. Mirror SQLite's
// SQLITE_DETERMINISTIC / SQLITE_DIRECTONLY / SQLITE_INNOCUOUS bits.
typedef uint8_t exports_sqlite_extension_types_function_flags_t;

// Same inputs always produce the same output.
#define EXPORTS_SQLITE_EXTENSION_TYPES_FUNCTION_FLAGS_DETERMINISTIC (1 << 0)
// May have side effects; cannot be used in indexes, CHECK
// constraints, generated columns, etc.
#define EXPORTS_SQLITE_EXTENSION_TYPES_FUNCTION_FLAGS_DIRECT_ONLY (1 << 1)
// Function is provably safe to use in arbitrary trusted SQL.
#define EXPORTS_SQLITE_EXTENSION_TYPES_FUNCTION_FLAGS_INNOCUOUS (1 << 2)

// Authorization action codes. Mirrors SQLite's SQLITE_* action
// constants passed to the authorizer callback.
typedef uint8_t exports_sqlite_extension_types_auth_action_t;

#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_INDEX 0
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TABLE 1
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TEMP_INDEX 2
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TEMP_TABLE 3
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TEMP_TRIGGER 4
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TEMP_VIEW 5
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TRIGGER 6
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_VIEW 7
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_DELETE 8
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_INDEX 9
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TABLE 10
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TEMP_INDEX 11
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TEMP_TABLE 12
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TEMP_TRIGGER 13
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TEMP_VIEW 14
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TRIGGER 15
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_VIEW 16
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_INSERT 17
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_PRAGMA 18
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_READ 19
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_SELECT 20
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_TRANSACTION 21
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_UPDATE 22
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_ATTACH 23
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_DETACH 24
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_ALTER_TABLE 25
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_REINDEX 26
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_ANALYZE 27
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_VTABLE 28
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_VTABLE 29
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_FUNCTION 30
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_SAVEPOINT 31
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_ACTION_RECURSIVE 32

// Result returned from an authorizer callback.
typedef uint8_t exports_sqlite_extension_types_auth_result_t;

// Permit the action.
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_RESULT_OK 0
// Deny the action with an error.
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_RESULT_DENY 1
// Silently ignore the action (treat as no-op).
#define EXPORTS_SQLITE_EXTENSION_TYPES_AUTH_RESULT_IGNORE 2

// Type of row change reported to an update hook.
typedef uint8_t exports_sqlite_extension_types_update_operation_t;

#define EXPORTS_SQLITE_EXTENSION_TYPES_UPDATE_OPERATION_INSERT 0
#define EXPORTS_SQLITE_EXTENSION_TYPES_UPDATE_OPERATION_UPDATE 1
#define EXPORTS_SQLITE_EXTENSION_TYPES_UPDATE_OPERATION_DELETE 2

// Log severity levels.
typedef uint8_t exports_sqlite_extension_types_log_level_t;

#define EXPORTS_SQLITE_EXTENSION_TYPES_LOG_LEVEL_ERROR 0
#define EXPORTS_SQLITE_EXTENSION_TYPES_LOG_LEVEL_WARN 1
#define EXPORTS_SQLITE_EXTENSION_TYPES_LOG_LEVEL_INFO 2
#define EXPORTS_SQLITE_EXTENSION_TYPES_LOG_LEVEL_DEBUG 3
#define EXPORTS_SQLITE_EXTENSION_TYPES_LOG_LEVEL_TRACE 4

// Per-column metadata returned by schema introspection.
typedef struct exports_sqlite_extension_types_column_info_t {
  sqlite_cli_unified_string_t   name;
  sqlite_cli_unified_option_string_t   decl_type;
  sqlite_cli_unified_option_string_t   database;
  sqlite_cli_unified_option_string_t   table;
  sqlite_cli_unified_option_string_t   origin;
} exports_sqlite_extension_types_column_info_t;

typedef struct {
  exports_sqlite_extension_types_column_info_t *ptr;
  size_t len;
} exports_sqlite_extension_types_list_column_info_t;

// Per-table metadata returned by schema introspection.
typedef struct exports_sqlite_extension_types_table_info_t {
  sqlite_cli_unified_string_t   name;
  exports_sqlite_extension_types_list_column_info_t   columns;
  sqlite_cli_unified_list_string_t   pk_columns;
} exports_sqlite_extension_types_table_info_t;

typedef struct {
  exports_sqlite_extension_types_sql_value_t *ptr;
  size_t len;
} exports_sqlite_extension_types_list_sql_value_t;

typedef struct {
  exports_sqlite_extension_types_list_sql_value_t *ptr;
  size_t len;
} exports_sqlite_extension_types_list_list_sql_value_t;

// Result of an `execute` call: column names, row data, change counts.
typedef struct exports_sqlite_extension_types_query_result_t {
  sqlite_cli_unified_list_string_t   columns;
  exports_sqlite_extension_types_list_list_sql_value_t   rows;
  // Rows changed by INSERT/UPDATE/DELETE.
  int64_t   changes;
  // Last inserted rowid.
  int64_t   last_insert_rowid;
} exports_sqlite_extension_types_query_result_t;

typedef exports_sqlite_extension_types_sql_value_t exports_sqlite_extension_spi_sql_value_t;

typedef exports_sqlite_extension_types_query_result_t exports_sqlite_extension_spi_query_result_t;

typedef exports_sqlite_extension_types_sqlite_error_t exports_sqlite_extension_spi_sqlite_error_t;

typedef struct {
  exports_sqlite_extension_spi_sql_value_t *ptr;
  size_t len;
} exports_sqlite_extension_spi_list_sql_value_t;

typedef struct {
  bool is_err;
  union {
    exports_sqlite_extension_spi_query_result_t ok;
    exports_sqlite_extension_spi_sqlite_error_t err;
  } val;
} exports_sqlite_extension_spi_result_query_result_sqlite_error_t;

typedef struct {
  bool is_err;
  union {
    exports_sqlite_extension_spi_sql_value_t ok;
    exports_sqlite_extension_spi_sqlite_error_t err;
  } val;
} exports_sqlite_extension_spi_result_sql_value_sqlite_error_t;

typedef struct {
  bool is_err;
  union {
    int64_t ok;
    exports_sqlite_extension_spi_sqlite_error_t err;
  } val;
} exports_sqlite_extension_spi_result_s64_sqlite_error_t;

typedef exports_sqlite_extension_types_log_level_t exports_sqlite_extension_logging_log_level_t;

// Imported Functions from `sqlite:extension/http@0.1.0`
// Send the request and wait for the full response.
extern bool sqlite_extension_http_handle(sqlite_extension_http_request_t *req, sqlite_extension_http_response_t *ret, sqlite_extension_http_http_error_t *err);

// Imported Functions from `sqlite:extension/metadata@0.1.0`
// Return the extension's full manifest. Called once by the host
// after instantiation, before any other guest function is dispatched.
extern void sqlite_extension_metadata_describe(sqlite_extension_metadata_manifest_t *ret);

// Imported Functions from `sqlite:wasm/fts5-slot@0.1.0`
extern void sqlite_wasm_fts5_slot_describe(sqlite_wasm_fts5_slot_manifest_t *ret);
extern bool sqlite_wasm_fts5_slot_call(uint64_t func_id, sqlite_wasm_fts5_slot_list_sql_value_t *args, sqlite_wasm_fts5_slot_sql_value_t *ret, sqlite_cli_unified_string_t *err);

// Imported Functions from `sqlite:wasm/json1-slot@0.1.0`
extern void sqlite_wasm_json1_slot_describe(sqlite_wasm_json1_slot_manifest_t *ret);
extern bool sqlite_wasm_json1_slot_call(uint64_t func_id, sqlite_wasm_json1_slot_list_sql_value_t *args, sqlite_wasm_json1_slot_sql_value_t *ret, sqlite_cli_unified_string_t *err);

// Imported Functions from `sqlite:wasm/rtree-slot@0.1.0`
extern void sqlite_wasm_rtree_slot_describe(sqlite_wasm_rtree_slot_manifest_t *ret);
extern bool sqlite_wasm_rtree_slot_call(uint64_t func_id, sqlite_wasm_rtree_slot_list_sql_value_t *args, sqlite_wasm_rtree_slot_sql_value_t *ret, sqlite_cli_unified_string_t *err);

// Imported Functions from `sqlite:wasm/geopoly-slot@0.1.0`
extern void sqlite_wasm_geopoly_slot_describe(sqlite_wasm_geopoly_slot_manifest_t *ret);
extern bool sqlite_wasm_geopoly_slot_call(uint64_t func_id, sqlite_wasm_geopoly_slot_list_sql_value_t *args, sqlite_wasm_geopoly_slot_sql_value_t *ret, sqlite_cli_unified_string_t *err);

// Imported Functions from `sqlite:wasm/demo-slot@0.1.0`
extern void sqlite_wasm_demo_slot_describe(sqlite_wasm_demo_slot_manifest_t *ret);
extern bool sqlite_wasm_demo_slot_call(uint64_t func_id, sqlite_wasm_demo_slot_list_sql_value_t *args, sqlite_wasm_demo_slot_sql_value_t *ret, sqlite_cli_unified_string_t *err);

// Imported Functions from `sqlite:wasm/extension-loader@0.1.0`
// Load a WASM extension component from a host path under the
// supplied policy. Returns the verified manifest on success — the
// same shape produced by metadata.describe().
extern bool sqlite_wasm_extension_loader_load_extension(sqlite_cli_unified_string_t *path, sqlite_wasm_extension_loader_load_options_t *options, sqlite_wasm_extension_loader_manifest_t *ret, sqlite_wasm_extension_loader_loader_error_t *err);
// Unload a previously loaded extension by name.
extern bool sqlite_wasm_extension_loader_unload_extension(sqlite_cli_unified_string_t *name, sqlite_wasm_extension_loader_loader_error_t *err);
// List currently loaded extensions as their manifests.
extern void sqlite_wasm_extension_loader_list_extensions(sqlite_wasm_extension_loader_list_manifest_t *ret);
// True iff an extension with the given name is currently loaded.
extern bool sqlite_wasm_extension_loader_is_extension_loaded(sqlite_cli_unified_string_t *name);

// Imported Functions from `sqlite:wasm/zip-operations@0.1.0`
// Create a new ZIP archive from files
extern bool sqlite_wasm_zip_operations_create_archive(sqlite_cli_unified_string_t *path, sqlite_wasm_zip_operations_error_code_t *err);
// Extract a ZIP archive to destination directory
extern bool sqlite_wasm_zip_operations_extract_archive(sqlite_cli_unified_string_t *path, sqlite_cli_unified_string_t *dest, sqlite_wasm_zip_operations_error_code_t *err);
// List contents of a ZIP archive
extern bool sqlite_wasm_zip_operations_list_contents(sqlite_cli_unified_string_t *path, sqlite_cli_unified_list_string_t *ret, sqlite_wasm_zip_operations_error_code_t *err);
// Get archive provider information
extern void sqlite_wasm_zip_operations_get_info(sqlite_wasm_zip_operations_archive_info_t *ret);

// Exported Functions from `sqlite:wasm/low-level@0.1.0`
bool exports_sqlite_wasm_low_level_open(sqlite_cli_unified_string_t *filename, exports_sqlite_wasm_low_level_open_flags_t open_flags, exports_sqlite_wasm_low_level_db_handle_t *ret, exports_sqlite_wasm_low_level_result_code_t *err);
exports_sqlite_wasm_low_level_result_code_t exports_sqlite_wasm_low_level_close(exports_sqlite_wasm_low_level_db_handle_t db);
bool exports_sqlite_wasm_low_level_exec(exports_sqlite_wasm_low_level_db_handle_t db, sqlite_cli_unified_string_t *sql, sqlite_cli_unified_string_t *ret, exports_sqlite_wasm_low_level_result_code_t *err);
bool exports_sqlite_wasm_low_level_prepare(exports_sqlite_wasm_low_level_db_handle_t db, sqlite_cli_unified_string_t *sql, exports_sqlite_wasm_low_level_stmt_handle_t *ret, exports_sqlite_wasm_low_level_result_code_t *err);
exports_sqlite_wasm_low_level_result_code_t exports_sqlite_wasm_low_level_step(exports_sqlite_wasm_low_level_stmt_handle_t stmt);
exports_sqlite_wasm_low_level_result_code_t exports_sqlite_wasm_low_level_reset(exports_sqlite_wasm_low_level_stmt_handle_t stmt);
exports_sqlite_wasm_low_level_result_code_t exports_sqlite_wasm_low_level_finalize(exports_sqlite_wasm_low_level_stmt_handle_t stmt);
exports_sqlite_wasm_low_level_result_code_t exports_sqlite_wasm_low_level_bind_null(exports_sqlite_wasm_low_level_stmt_handle_t stmt, int32_t index);
exports_sqlite_wasm_low_level_result_code_t exports_sqlite_wasm_low_level_bind_int(exports_sqlite_wasm_low_level_stmt_handle_t stmt, int32_t index, int32_t value);
exports_sqlite_wasm_low_level_result_code_t exports_sqlite_wasm_low_level_bind_int64(exports_sqlite_wasm_low_level_stmt_handle_t stmt, int32_t index, int64_t value);
exports_sqlite_wasm_low_level_result_code_t exports_sqlite_wasm_low_level_bind_double(exports_sqlite_wasm_low_level_stmt_handle_t stmt, int32_t index, double value);
exports_sqlite_wasm_low_level_result_code_t exports_sqlite_wasm_low_level_bind_text(exports_sqlite_wasm_low_level_stmt_handle_t stmt, int32_t index, sqlite_cli_unified_string_t *value);
exports_sqlite_wasm_low_level_result_code_t exports_sqlite_wasm_low_level_bind_blob(exports_sqlite_wasm_low_level_stmt_handle_t stmt, int32_t index, sqlite_cli_unified_list_u8_t *value);
int32_t exports_sqlite_wasm_low_level_bind_parameter_count(exports_sqlite_wasm_low_level_stmt_handle_t stmt);
int32_t exports_sqlite_wasm_low_level_bind_parameter_index(exports_sqlite_wasm_low_level_stmt_handle_t stmt, sqlite_cli_unified_string_t *name);
exports_sqlite_wasm_low_level_result_code_t exports_sqlite_wasm_low_level_clear_bindings(exports_sqlite_wasm_low_level_stmt_handle_t stmt);
int32_t exports_sqlite_wasm_low_level_column_count(exports_sqlite_wasm_low_level_stmt_handle_t stmt);
void exports_sqlite_wasm_low_level_column_name(exports_sqlite_wasm_low_level_stmt_handle_t stmt, int32_t index, sqlite_cli_unified_string_t *ret);
exports_sqlite_wasm_low_level_column_type_t exports_sqlite_wasm_low_level_get_column_type(exports_sqlite_wasm_low_level_stmt_handle_t stmt, int32_t index);
int32_t exports_sqlite_wasm_low_level_column_int(exports_sqlite_wasm_low_level_stmt_handle_t stmt, int32_t index);
int64_t exports_sqlite_wasm_low_level_column_int64(exports_sqlite_wasm_low_level_stmt_handle_t stmt, int32_t index);
double exports_sqlite_wasm_low_level_column_double(exports_sqlite_wasm_low_level_stmt_handle_t stmt, int32_t index);
void exports_sqlite_wasm_low_level_column_text(exports_sqlite_wasm_low_level_stmt_handle_t stmt, int32_t index, sqlite_cli_unified_string_t *ret);
void exports_sqlite_wasm_low_level_column_blob(exports_sqlite_wasm_low_level_stmt_handle_t stmt, int32_t index, sqlite_cli_unified_list_u8_t *ret);
int32_t exports_sqlite_wasm_low_level_column_bytes(exports_sqlite_wasm_low_level_stmt_handle_t stmt, int32_t index);
void exports_sqlite_wasm_low_level_errmsg(exports_sqlite_wasm_low_level_db_handle_t db, sqlite_cli_unified_string_t *ret);
exports_sqlite_wasm_low_level_result_code_t exports_sqlite_wasm_low_level_errcode(exports_sqlite_wasm_low_level_db_handle_t db);
int32_t exports_sqlite_wasm_low_level_extended_errcode(exports_sqlite_wasm_low_level_db_handle_t db);
bool exports_sqlite_wasm_low_level_get_autocommit(exports_sqlite_wasm_low_level_db_handle_t db);
int32_t exports_sqlite_wasm_low_level_changes(exports_sqlite_wasm_low_level_db_handle_t db);
int32_t exports_sqlite_wasm_low_level_total_changes(exports_sqlite_wasm_low_level_db_handle_t db);
int64_t exports_sqlite_wasm_low_level_last_insert_rowid(exports_sqlite_wasm_low_level_db_handle_t db);
void exports_sqlite_wasm_low_level_libversion(sqlite_cli_unified_string_t *ret);
int32_t exports_sqlite_wasm_low_level_libversion_number(void);
void exports_sqlite_wasm_low_level_sourceid(sqlite_cli_unified_string_t *ret);

// Exported Functions from `sqlite:wasm/high-level@0.1.0`
exports_sqlite_wasm_high_level_own_connection_t exports_sqlite_wasm_high_level_constructor_connection(sqlite_cli_unified_string_t *path, exports_sqlite_wasm_high_level_open_mode_t mode);
bool exports_sqlite_wasm_high_level_method_connection_execute(exports_sqlite_wasm_high_level_borrow_connection_t self, sqlite_cli_unified_string_t *sql, exports_sqlite_wasm_high_level_exec_result_t *ret, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_method_connection_execute_with_params(exports_sqlite_wasm_high_level_borrow_connection_t self, sqlite_cli_unified_string_t *sql, exports_sqlite_wasm_high_level_list_value_t *params, exports_sqlite_wasm_high_level_exec_result_t *ret, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_method_connection_query(exports_sqlite_wasm_high_level_borrow_connection_t self, sqlite_cli_unified_string_t *sql, exports_sqlite_wasm_high_level_query_result_t *ret, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_method_connection_query_with_params(exports_sqlite_wasm_high_level_borrow_connection_t self, sqlite_cli_unified_string_t *sql, exports_sqlite_wasm_high_level_list_value_t *params, exports_sqlite_wasm_high_level_query_result_t *ret, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_method_connection_prepare(exports_sqlite_wasm_high_level_borrow_connection_t self, sqlite_cli_unified_string_t *sql, exports_sqlite_wasm_high_level_own_statement_t *ret, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_method_connection_begin_transaction(exports_sqlite_wasm_high_level_borrow_connection_t self, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_method_connection_commit(exports_sqlite_wasm_high_level_borrow_connection_t self, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_method_connection_rollback(exports_sqlite_wasm_high_level_borrow_connection_t self, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_method_connection_in_autocommit(exports_sqlite_wasm_high_level_borrow_connection_t self);
bool exports_sqlite_wasm_high_level_method_connection_last_error(exports_sqlite_wasm_high_level_borrow_connection_t self, exports_sqlite_wasm_high_level_database_error_t *ret);
bool exports_sqlite_wasm_high_level_method_statement_bind(exports_sqlite_wasm_high_level_borrow_statement_t self, int32_t index, exports_sqlite_wasm_high_level_value_t *value, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_method_statement_bind_all(exports_sqlite_wasm_high_level_borrow_statement_t self, exports_sqlite_wasm_high_level_list_value_t *params, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_method_statement_execute(exports_sqlite_wasm_high_level_borrow_statement_t self, exports_sqlite_wasm_high_level_exec_result_t *ret, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_method_statement_query(exports_sqlite_wasm_high_level_borrow_statement_t self, exports_sqlite_wasm_high_level_query_result_t *ret, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_method_statement_step(exports_sqlite_wasm_high_level_borrow_statement_t self, exports_sqlite_wasm_high_level_option_row_t *ret, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_method_statement_reset(exports_sqlite_wasm_high_level_borrow_statement_t self, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_method_statement_clear_bindings(exports_sqlite_wasm_high_level_borrow_statement_t self, exports_sqlite_wasm_high_level_database_error_t *err);
int32_t exports_sqlite_wasm_high_level_method_statement_column_count(exports_sqlite_wasm_high_level_borrow_statement_t self);
void exports_sqlite_wasm_high_level_method_statement_column_names(exports_sqlite_wasm_high_level_borrow_statement_t self, sqlite_cli_unified_list_string_t *ret);
int32_t exports_sqlite_wasm_high_level_method_statement_parameter_count(exports_sqlite_wasm_high_level_borrow_statement_t self);
void exports_sqlite_wasm_high_level_version(sqlite_cli_unified_string_t *ret);
int32_t exports_sqlite_wasm_high_level_version_number(void);
bool exports_sqlite_wasm_high_level_open_memory(exports_sqlite_wasm_high_level_own_connection_t *ret, exports_sqlite_wasm_high_level_database_error_t *err);
bool exports_sqlite_wasm_high_level_open_file(sqlite_cli_unified_string_t *path, exports_sqlite_wasm_high_level_own_connection_t *ret, exports_sqlite_wasm_high_level_database_error_t *err);

// Exported Functions from `sqlite:extension/spi@0.1.0`
bool exports_sqlite_extension_spi_execute(sqlite_cli_unified_string_t *sql, exports_sqlite_extension_spi_list_sql_value_t *params, exports_sqlite_extension_spi_query_result_t *ret, exports_sqlite_extension_spi_sqlite_error_t *err);
bool exports_sqlite_extension_spi_execute_scalar(sqlite_cli_unified_string_t *sql, exports_sqlite_extension_spi_list_sql_value_t *params, exports_sqlite_extension_spi_sql_value_t *ret, exports_sqlite_extension_spi_sqlite_error_t *err);
bool exports_sqlite_extension_spi_execute_batch(sqlite_cli_unified_string_t *sql, int64_t *ret, exports_sqlite_extension_spi_sqlite_error_t *err);

// Exported Functions from `sqlite:extension/logging@0.1.0`
void exports_sqlite_extension_logging_log(exports_sqlite_extension_logging_log_level_t level, sqlite_cli_unified_string_t *message);
void exports_sqlite_extension_logging_error(sqlite_cli_unified_string_t *message);
void exports_sqlite_extension_logging_warn(sqlite_cli_unified_string_t *message);
void exports_sqlite_extension_logging_info(sqlite_cli_unified_string_t *message);
void exports_sqlite_extension_logging_debug(sqlite_cli_unified_string_t *message);

// Exported Functions from `sqlite:extension/config@0.1.0`
bool exports_sqlite_extension_config_get(sqlite_cli_unified_string_t *key, sqlite_cli_unified_string_t *ret);
bool exports_sqlite_extension_config_set(sqlite_cli_unified_string_t *key, sqlite_cli_unified_string_t *value);
void exports_sqlite_extension_config_sqlite_version(sqlite_cli_unified_string_t *ret);
void exports_sqlite_extension_config_extension_version(sqlite_cli_unified_string_t *ret);

// Helper Functions

void sqlite_cli_unified_list_u8_free(sqlite_cli_unified_list_u8_t *ptr);

void sqlite_extension_types_sql_value_free(sqlite_extension_types_sql_value_t *ptr);

void sqlite_extension_types_sqlite_error_free(sqlite_extension_types_sqlite_error_t *ptr);

void sqlite_cli_unified_option_string_free(sqlite_cli_unified_option_string_t *ptr);

void sqlite_extension_types_column_info_free(sqlite_extension_types_column_info_t *ptr);

void sqlite_extension_types_list_column_info_free(sqlite_extension_types_list_column_info_t *ptr);

void sqlite_cli_unified_list_string_free(sqlite_cli_unified_list_string_t *ptr);

void sqlite_extension_types_table_info_free(sqlite_extension_types_table_info_t *ptr);

void sqlite_extension_types_list_sql_value_free(sqlite_extension_types_list_sql_value_t *ptr);

void sqlite_extension_types_list_list_sql_value_free(sqlite_extension_types_list_list_sql_value_t *ptr);

void sqlite_extension_types_query_result_free(sqlite_extension_types_query_result_t *ptr);

void sqlite_extension_http_method_free(sqlite_extension_http_method_t *ptr);

void sqlite_extension_http_scheme_free(sqlite_extension_http_scheme_t *ptr);

void sqlite_extension_http_field_free(sqlite_extension_http_field_t *ptr);

void sqlite_extension_http_option_scheme_free(sqlite_extension_http_option_scheme_t *ptr);

void sqlite_cli_unified_list_field_free(sqlite_cli_unified_list_field_t *ptr);

void sqlite_cli_unified_option_list_u8_free(sqlite_cli_unified_option_list_u8_t *ptr);

void sqlite_cli_unified_option_u32_free(sqlite_cli_unified_option_u32_t *ptr);

void sqlite_extension_http_request_free(sqlite_extension_http_request_t *ptr);

void sqlite_extension_http_response_free(sqlite_extension_http_response_t *ptr);

void sqlite_extension_http_http_error_free(sqlite_extension_http_http_error_t *ptr);

void sqlite_extension_http_result_response_http_error_free(sqlite_extension_http_result_response_http_error_t *ptr);

void sqlite_extension_policy_method_free(sqlite_extension_policy_method_t *ptr);

void sqlite_extension_policy_capability_free(sqlite_extension_policy_capability_t *ptr);

void sqlite_extension_policy_list_method_free(sqlite_extension_policy_list_method_t *ptr);

void sqlite_extension_policy_option_list_method_free(sqlite_extension_policy_option_list_method_t *ptr);

void sqlite_cli_unified_option_u64_free(sqlite_cli_unified_option_u64_t *ptr);

void sqlite_extension_policy_http_policy_free(sqlite_extension_policy_http_policy_t *ptr);

void sqlite_extension_policy_fs_policy_free(sqlite_extension_policy_fs_policy_t *ptr);

void sqlite_extension_policy_option_http_policy_free(sqlite_extension_policy_option_http_policy_t *ptr);

void sqlite_extension_policy_option_fs_policy_free(sqlite_extension_policy_option_fs_policy_t *ptr);

void sqlite_extension_policy_list_capability_free(sqlite_extension_policy_list_capability_t *ptr);

void sqlite_extension_policy_load_options_free(sqlite_extension_policy_load_options_t *ptr);

void sqlite_extension_policy_policy_error_free(sqlite_extension_policy_policy_error_t *ptr);

void sqlite_extension_metadata_capability_free(sqlite_extension_metadata_capability_t *ptr);

void sqlite_extension_metadata_scalar_function_spec_free(sqlite_extension_metadata_scalar_function_spec_t *ptr);

void sqlite_extension_metadata_aggregate_function_spec_free(sqlite_extension_metadata_aggregate_function_spec_t *ptr);

void sqlite_extension_metadata_collation_spec_free(sqlite_extension_metadata_collation_spec_t *ptr);

void sqlite_extension_metadata_list_scalar_function_spec_free(sqlite_extension_metadata_list_scalar_function_spec_t *ptr);

void sqlite_extension_metadata_list_aggregate_function_spec_free(sqlite_extension_metadata_list_aggregate_function_spec_t *ptr);

void sqlite_extension_metadata_list_collation_spec_free(sqlite_extension_metadata_list_collation_spec_t *ptr);

void sqlite_extension_metadata_list_capability_free(sqlite_extension_metadata_list_capability_t *ptr);

void sqlite_extension_metadata_manifest_free(sqlite_extension_metadata_manifest_t *ptr);

void sqlite_wasm_fts5_slot_sql_value_free(sqlite_wasm_fts5_slot_sql_value_t *ptr);

void sqlite_wasm_fts5_slot_manifest_free(sqlite_wasm_fts5_slot_manifest_t *ptr);

void sqlite_wasm_fts5_slot_list_sql_value_free(sqlite_wasm_fts5_slot_list_sql_value_t *ptr);

void sqlite_wasm_fts5_slot_result_sql_value_string_free(sqlite_wasm_fts5_slot_result_sql_value_string_t *ptr);

void sqlite_wasm_json1_slot_sql_value_free(sqlite_wasm_json1_slot_sql_value_t *ptr);

void sqlite_wasm_json1_slot_manifest_free(sqlite_wasm_json1_slot_manifest_t *ptr);

void sqlite_wasm_json1_slot_list_sql_value_free(sqlite_wasm_json1_slot_list_sql_value_t *ptr);

void sqlite_wasm_json1_slot_result_sql_value_string_free(sqlite_wasm_json1_slot_result_sql_value_string_t *ptr);

void sqlite_wasm_rtree_slot_sql_value_free(sqlite_wasm_rtree_slot_sql_value_t *ptr);

void sqlite_wasm_rtree_slot_manifest_free(sqlite_wasm_rtree_slot_manifest_t *ptr);

void sqlite_wasm_rtree_slot_list_sql_value_free(sqlite_wasm_rtree_slot_list_sql_value_t *ptr);

void sqlite_wasm_rtree_slot_result_sql_value_string_free(sqlite_wasm_rtree_slot_result_sql_value_string_t *ptr);

void sqlite_wasm_geopoly_slot_sql_value_free(sqlite_wasm_geopoly_slot_sql_value_t *ptr);

void sqlite_wasm_geopoly_slot_manifest_free(sqlite_wasm_geopoly_slot_manifest_t *ptr);

void sqlite_wasm_geopoly_slot_list_sql_value_free(sqlite_wasm_geopoly_slot_list_sql_value_t *ptr);

void sqlite_wasm_geopoly_slot_result_sql_value_string_free(sqlite_wasm_geopoly_slot_result_sql_value_string_t *ptr);

void sqlite_wasm_demo_slot_sql_value_free(sqlite_wasm_demo_slot_sql_value_t *ptr);

void sqlite_wasm_demo_slot_manifest_free(sqlite_wasm_demo_slot_manifest_t *ptr);

void sqlite_wasm_demo_slot_list_sql_value_free(sqlite_wasm_demo_slot_list_sql_value_t *ptr);

void sqlite_wasm_demo_slot_result_sql_value_string_free(sqlite_wasm_demo_slot_result_sql_value_string_t *ptr);

void sqlite_wasm_extension_loader_manifest_free(sqlite_wasm_extension_loader_manifest_t *ptr);

void sqlite_wasm_extension_loader_load_options_free(sqlite_wasm_extension_loader_load_options_t *ptr);

void sqlite_wasm_extension_loader_loader_error_free(sqlite_wasm_extension_loader_loader_error_t *ptr);

void sqlite_wasm_extension_loader_result_manifest_loader_error_free(sqlite_wasm_extension_loader_result_manifest_loader_error_t *ptr);

void sqlite_wasm_extension_loader_result_void_loader_error_free(sqlite_wasm_extension_loader_result_void_loader_error_t *ptr);

void sqlite_wasm_extension_loader_list_manifest_free(sqlite_wasm_extension_loader_list_manifest_t *ptr);

void sqlite_wasm_zip_operations_archive_info_free(sqlite_wasm_zip_operations_archive_info_t *ptr);

void sqlite_wasm_zip_operations_result_void_error_code_free(sqlite_wasm_zip_operations_result_void_error_code_t *ptr);

void sqlite_wasm_zip_operations_result_list_string_error_code_free(sqlite_wasm_zip_operations_result_list_string_error_code_t *ptr);

void exports_sqlite_wasm_low_level_result_db_handle_result_code_free(exports_sqlite_wasm_low_level_result_db_handle_result_code_t *ptr);

void exports_sqlite_wasm_low_level_result_string_result_code_free(exports_sqlite_wasm_low_level_result_string_result_code_t *ptr);

void exports_sqlite_wasm_low_level_result_stmt_handle_result_code_free(exports_sqlite_wasm_low_level_result_stmt_handle_result_code_t *ptr);

void exports_sqlite_wasm_high_level_value_free(exports_sqlite_wasm_high_level_value_t *ptr);

void exports_sqlite_wasm_high_level_database_error_free(exports_sqlite_wasm_high_level_database_error_t *ptr);

void exports_sqlite_wasm_high_level_list_value_free(exports_sqlite_wasm_high_level_list_value_t *ptr);

void exports_sqlite_wasm_high_level_row_free(exports_sqlite_wasm_high_level_row_t *ptr);

void exports_sqlite_wasm_high_level_list_row_free(exports_sqlite_wasm_high_level_list_row_t *ptr);

void exports_sqlite_wasm_high_level_query_result_free(exports_sqlite_wasm_high_level_query_result_t *ptr);

extern void exports_sqlite_wasm_high_level_connection_drop_own(exports_sqlite_wasm_high_level_own_connection_t handle);

extern exports_sqlite_wasm_high_level_own_connection_t exports_sqlite_wasm_high_level_connection_new(exports_sqlite_wasm_high_level_connection_t *rep);
extern exports_sqlite_wasm_high_level_connection_t* exports_sqlite_wasm_high_level_connection_rep(exports_sqlite_wasm_high_level_own_connection_t handle);
void exports_sqlite_wasm_high_level_connection_destructor(exports_sqlite_wasm_high_level_connection_t *rep);

extern void exports_sqlite_wasm_high_level_statement_drop_own(exports_sqlite_wasm_high_level_own_statement_t handle);

extern exports_sqlite_wasm_high_level_own_statement_t exports_sqlite_wasm_high_level_statement_new(exports_sqlite_wasm_high_level_statement_t *rep);
extern exports_sqlite_wasm_high_level_statement_t* exports_sqlite_wasm_high_level_statement_rep(exports_sqlite_wasm_high_level_own_statement_t handle);
void exports_sqlite_wasm_high_level_statement_destructor(exports_sqlite_wasm_high_level_statement_t *rep);

void exports_sqlite_wasm_high_level_result_exec_result_database_error_free(exports_sqlite_wasm_high_level_result_exec_result_database_error_t *ptr);

void exports_sqlite_wasm_high_level_result_query_result_database_error_free(exports_sqlite_wasm_high_level_result_query_result_database_error_t *ptr);

void exports_sqlite_wasm_high_level_result_own_statement_database_error_free(exports_sqlite_wasm_high_level_result_own_statement_database_error_t *ptr);

void exports_sqlite_wasm_high_level_result_void_database_error_free(exports_sqlite_wasm_high_level_result_void_database_error_t *ptr);

void exports_sqlite_wasm_high_level_option_database_error_free(exports_sqlite_wasm_high_level_option_database_error_t *ptr);

void exports_sqlite_wasm_high_level_option_row_free(exports_sqlite_wasm_high_level_option_row_t *ptr);

void exports_sqlite_wasm_high_level_result_option_row_database_error_free(exports_sqlite_wasm_high_level_result_option_row_database_error_t *ptr);

void exports_sqlite_wasm_high_level_result_own_connection_database_error_free(exports_sqlite_wasm_high_level_result_own_connection_database_error_t *ptr);

void exports_sqlite_extension_types_sql_value_free(exports_sqlite_extension_types_sql_value_t *ptr);

void exports_sqlite_extension_types_sqlite_error_free(exports_sqlite_extension_types_sqlite_error_t *ptr);

void exports_sqlite_extension_types_column_info_free(exports_sqlite_extension_types_column_info_t *ptr);

void exports_sqlite_extension_types_list_column_info_free(exports_sqlite_extension_types_list_column_info_t *ptr);

void exports_sqlite_extension_types_table_info_free(exports_sqlite_extension_types_table_info_t *ptr);

void exports_sqlite_extension_types_list_sql_value_free(exports_sqlite_extension_types_list_sql_value_t *ptr);

void exports_sqlite_extension_types_list_list_sql_value_free(exports_sqlite_extension_types_list_list_sql_value_t *ptr);

void exports_sqlite_extension_types_query_result_free(exports_sqlite_extension_types_query_result_t *ptr);

void exports_sqlite_extension_spi_sql_value_free(exports_sqlite_extension_spi_sql_value_t *ptr);

void exports_sqlite_extension_spi_query_result_free(exports_sqlite_extension_spi_query_result_t *ptr);

void exports_sqlite_extension_spi_sqlite_error_free(exports_sqlite_extension_spi_sqlite_error_t *ptr);

void exports_sqlite_extension_spi_list_sql_value_free(exports_sqlite_extension_spi_list_sql_value_t *ptr);

void exports_sqlite_extension_spi_result_query_result_sqlite_error_free(exports_sqlite_extension_spi_result_query_result_sqlite_error_t *ptr);

void exports_sqlite_extension_spi_result_sql_value_sqlite_error_free(exports_sqlite_extension_spi_result_sql_value_sqlite_error_t *ptr);

void exports_sqlite_extension_spi_result_s64_sqlite_error_free(exports_sqlite_extension_spi_result_s64_sqlite_error_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void sqlite_cli_unified_string_set(sqlite_cli_unified_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void sqlite_cli_unified_string_dup(sqlite_cli_unified_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void sqlite_cli_unified_string_free(sqlite_cli_unified_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
